from app.core.base import BaseRepository
from .admin_audit_log_repository import AdminAuditLogRepository
from .admin_identity_repository import AdminIdentityRepository
from .admin_permission_repository import AdminPermissionRepository
from .admin_role_repository import AdminRoleRepository
from .error_log_repository import ErrorLogRepository
from .ip_rule_repository import IpRuleRepository
from .security_event_repository import SecurityEventRepository
